#[allow(non_camel_case_types)]
#[derive(PartialEq)]
#[derive(Debug)]
pub enum Token {
    ILLEGAL,
    EOF,
    K_A,                // "a"
    K_ABBR,             // "abbr"
    K_ACRONYM,          // "acronym"
    K_ADDRESS,          // "address"
    K_APPLET,           // "applet"
    K_AREA,             // "area"
    K_ARTICLE,          // "article"
    K_ASIDE,            // "aside"
    K_AUDIO,            // "audio"
    K_B,                // "b"
    K_BASE,             // "base"
    K_BASEFONT,         // "basefont"
    K_BB,               // "bb"
    K_BDO,              // "bdo"
    K_BIG,              // "big"
    K_BLOCKQUOTE,       // "blockquote"
    K_BODY,             // "body"
    K_BR,               // "br"
    K_BUTTON,           // "button"
    K_CANVAS,           // "canvas"
    K_CAPTION,          // "caption"
    K_CENTER,           // "center"
    K_CITE,             // "cite"
    K_CODE,             // "code"
    K_COL,              // "col"
    K_COLGROUP,         // "colgroup"
    K_COMMAND,          // "command"
    K_DATAGRID,         // "datagrid"
    K_DATALIST,         // "datalist"
    K_DD,               // "dd"
    K_DEL,              // "del"
    K_DETAILS,          // "details"
    K_DFN,              // "dfn"
    K_DIALOG,           // "dialog"
    K_DIR,              // "dir"
    K_DIV,              // "div"
    K_DL,               // "dl"
    K_DT,               // "dt"
    K_EM,               // "em"
    K_EMBED,            // "embed"
    K_EVENTSOURCE,      // "eventsource"
    K_FIELDSET,         // "fieldset"
    K_FIGCAPTION,       // "figcaption"
    K_FIGURE,           // "figure"
    K_FONT,             // "font"
    K_FOOTER,           // "footer"
    K_FORM,             // "form"
    K_FRAME,            // "frame"
    K_FRAMESET,         // "frameset"
    K_H1,               // "h1"
    K_HEAD,             // "head"
    K_HEADER,           // "header"
    K_HGROUP,           // "hgroup"
    K_HR,               // "hr"
    K_HTML,             // "html"
    K_I,                // "i"
    K_IFRAME,           // "iframe"
    K_IMG,              // "img"
    K_INPUT,            // "input"
    K_INS,              // "ins"
    K_ISINDEX,          // "isindex"
    K_KBD,              // "kbd"
    K_KEYGEN,           // "keygen"
    K_LABEL,            // "label"
    K_LEGEND,           // "legend"
    K_LI,               // "li"
    K_LINK,             // "link"
    K_MAP,              // "map"
    K_MARK,             // "mark"
    K_MENU,             // "menu"
    K_META,             // "meta"
    K_METER,            // "meter"
    K_NAV,              // "nav"
    K_NOFRAMES,         // "noframes"
    K_NOSCRIPT,         // "noscript"
    K_OBJECT,           // "object"
    K_OL,               // "ol"
    K_OPTGROUP,         // "optgroup"
    K_OPTION,           // "option"
    K_OUTPUT,           // "output"
    K_P,                // "p"
    K_PARAM,            // "param"
    K_PRE,              // "pre"
    K_PROGRESS,         // "progress"
    K_Q,                // "q"
    K_RP,               // "rp"
    K_RT,               // "rt"
    K_RUBY,             // "ruby"
    K_S,                // "s"
    K_SAMP,             // "samp"
    K_SCRIPT,           // "script"
    K_SECTION,          // "section"
    K_SELECT,           // "select"
    K_SMALL,            // "small"
    K_SOURCE,           // "source"
    K_SPAN,             // "span"
    K_STRIKE,           // "strike"
    K_STRONG,           // "strong"
    K_STYLE,            // "style"
    K_SUB,              // "sub"
    K_SUP,              // "sup"
    K_TABLE,            // "table"
    K_TBODY,            // "tbody"
    K_TD,               // "td"
    K_TEXTAREA,         // "textarea"
    K_TFOOT,            // "tfoot"
    K_TH,               // "th"
    K_THEAD,            // "thead"
    K_TIME,             // "time"
    K_TITLE,            // "title"
    K_TR,               // "tr"
    K_TRACK,            // "track"
    K_TT,               // "tt"
    K_U,                // "u"
    K_UL,               // "ul"
    K_VAR,              // "var"
    K_VIDEO,            // "video"
    K_WBR,              // "wbr"
    WORD(Vec<char>),
    INT(Vec<char>),     // 123..
    LBRACE(char),       // {
    RBRACE(char),       // }
    ASTERISK(char),     // *
    SMALLERTHAN(char),  // <
    GREATERTHAN(char)   // >
}

pub fn get_keyword(word: &Vec<char>) -> Result<Token, String> {
    let word: String = word.into_iter().collect();
 
    match &word[..] {
        "a"             => Ok(Token::K_A),
        "abbr"          => Ok(Token::K_ABBR),
        "acronym"       => Ok(Token::K_ACRONYM),
        "address"       => Ok(Token::K_ADDRESS),
        "applet"        => Ok(Token::K_APPLET),
        "area"          => Ok(Token::K_AREA),
        "article"       => Ok(Token::K_ARTICLE),
        "aside"         => Ok(Token::K_ASIDE),
        "audio"         => Ok(Token::K_AUDIO),
        "b"             => Ok(Token::K_B),
        "base"          => Ok(Token::K_BASE),
        "basefont"      => Ok(Token::K_BASEFONT),
        "bb"            => Ok(Token::K_BB),
        "bdo"           => Ok(Token::K_BDO),
        "big"           => Ok(Token::K_BIG),
        "blockquote"    => Ok(Token::K_BLOCKQUOTE),
        "body"          => Ok(Token::K_BODY),
        "br"            => Ok(Token::K_BR),
        "button"        => Ok(Token::K_BUTTON),
        "canvas"        => Ok(Token::K_CANVAS),
        "caption"       => Ok(Token::K_CAPTION),
        "center"        => Ok(Token::K_CENTER),
        "cite"          => Ok(Token::K_CITE),
        "code"          => Ok(Token::K_CODE),
        "col"           => Ok(Token::K_COL),
        "colgroup"      => Ok(Token::K_COLGROUP),
        "command"       => Ok(Token::K_COMMAND),
        "datagrid"      => Ok(Token::K_DATAGRID),
        "datalist"      => Ok(Token::K_DATALIST),
        "dd"            => Ok(Token::K_DD),
        "del"           => Ok(Token::K_DEL),
        "details"       => Ok(Token::K_DETAILS),
        "dfn"           => Ok(Token::K_DFN),
        "dialog"        => Ok(Token::K_DIALOG),
        "dir"           => Ok(Token::K_DIR),
        "div"           => Ok(Token::K_DIV),
        "dl"            => Ok(Token::K_DL),
        "dt"            => Ok(Token::K_DT),
        "em"            => Ok(Token::K_EM),
        "embed"         => Ok(Token::K_EMBED),
        "eventsource"   => Ok(Token::K_EVENTSOURCE),
        "fieldset"      => Ok(Token::K_FIELDSET),
        "figcaption"    => Ok(Token::K_FIGCAPTION),
        "figure"        => Ok(Token::K_FIGURE),
        "font"          => Ok(Token::K_FONT),
        "footer"        => Ok(Token::K_FOOTER),
        "form"          => Ok(Token::K_FORM),
        "frame"         => Ok(Token::K_FRAME),
        "frameset"      => Ok(Token::K_FRAMESET),
        "h1"            => Ok(Token::K_H1),
        "head"          => Ok(Token::K_HEAD),
        "header"        => Ok(Token::K_HEADER),
        "hgroup"        => Ok(Token::K_HGROUP),
        "hr"            => Ok(Token::K_HR),
        "html"          => Ok(Token::K_HTML),
        "i"             => Ok(Token::K_I),
        "iframe"        => Ok(Token::K_IFRAME),
        "img"           => Ok(Token::K_IMG),
        "input"         => Ok(Token::K_INPUT),
        "ins"           => Ok(Token::K_INS),
        "isindex"       => Ok(Token::K_ISINDEX),
        "kbd"           => Ok(Token::K_KBD),
        "keygen"        => Ok(Token::K_KEYGEN),
        "label"         => Ok(Token::K_LABEL),
        "legend"        => Ok(Token::K_LEGEND),
        "li"            => Ok(Token::K_LI),
        "link"          => Ok(Token::K_LINK),
        "map"           => Ok(Token::K_MAP),
        "mark"          => Ok(Token::K_MARK),
        "menu"          => Ok(Token::K_MENU),
        "meta"          => Ok(Token::K_META),
        "meter"         => Ok(Token::K_METER),
        "nav"           => Ok(Token::K_NAV),
        "noframes"      => Ok(Token::K_NOFRAMES),
        "noscript"      => Ok(Token::K_NOSCRIPT),
        "object"        => Ok(Token::K_OBJECT),
        "ol"            => Ok(Token::K_OL),
        "optgroup"      => Ok(Token::K_OPTGROUP),
        "option"        => Ok(Token::K_OPTION),
        "output"        => Ok(Token::K_OUTPUT),
        "p"             => Ok(Token::K_P),
        "param"         => Ok(Token::K_PARAM),
        "pre"           => Ok(Token::K_PRE),
        "progress"      => Ok(Token::K_PROGRESS),
        "q"             => Ok(Token::K_Q),
        "rp"            => Ok(Token::K_RP),
        "rt"            => Ok(Token::K_RT),
        "ruby"          => Ok(Token::K_RUBY),
        "s"             => Ok(Token::K_S),
        "samp"          => Ok(Token::K_SAMP),
        "script"        => Ok(Token::K_SCRIPT),
        "section"       => Ok(Token::K_SECTION),
        "select"        => Ok(Token::K_SELECT),
        "small"         => Ok(Token::K_SMALL),
        "source"        => Ok(Token::K_SOURCE),
        "span"          => Ok(Token::K_SPAN),
        "strike"        => Ok(Token::K_STRIKE),
        "strong"        => Ok(Token::K_STRONG),
        "style"         => Ok(Token::K_STYLE),
        "sub"           => Ok(Token::K_SUB),
        "sup"           => Ok(Token::K_SUP),
        "table"         => Ok(Token::K_TABLE),
        "tbody"         => Ok(Token::K_TBODY),
        "td"            => Ok(Token::K_TD),
        "textarea"      => Ok(Token::K_TEXTAREA),
        "tfoot"         => Ok(Token::K_TFOOT),
        "th"            => Ok(Token::K_TH),
        "thead"         => Ok(Token::K_THEAD),
        "time"          => Ok(Token::K_TIME),
        "title"         => Ok(Token::K_TITLE),
        "tr"            => Ok(Token::K_TR),
        "track"         => Ok(Token::K_TRACK),
        "tt"            => Ok(Token::K_TT),
        "u"             => Ok(Token::K_U),
        "ul"            => Ok(Token::K_UL),
        "var"           => Ok(Token::K_VAR),
        "video"         => Ok(Token::K_VIDEO),
        "wbr"           => Ok(Token::K_WBR),
        // se nenhum dos matchs forem satisfeitos, não é uma palavra chave
        _ => Err(String::from("not a keyword"))
    }
}